name: learning_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS
  cupertino_icons: ^1.0.8

  # --- STUDY APP DEPENDENCIES ---
  google_fonts: ^6.1.0
  url_launcher: ^6.2.0
  http: ^1.1.0
  # glassmorphism: ^3.0.0  <-- You can actually remove this if you want, we styled it manually!

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true